'use strict';
const $=s=>document.querySelector(s);
const experiences=[
 {id:'vinhedo',city:'Bento Gonçalves',category:'wine',price:145,hours:2,image:'photo-1504279577054-acfeccf8fc52',title:['Entre taças e vinhedos','Entre copas y viñedos'],description:['Uma caminhada pela terra, seguida de uma degustação guiada.','Un paseo por la tierra, seguido de una degustación guiada.']},
 {id:'mesa',city:'Bento Gonçalves',category:'food',price:220,hours:3,image:'photo-1414235077428-338989a2e8c0',title:['A mesa da nonna','La mesa de la nonna'],description:['Receitas de família e uma longa conversa à mesa.','Recetas de familia y una larga conversación en la mesa.']},
 {id:'piquenique',city:'Pinto Bandeira',category:'nature',price:125,hours:2,image:'photo-1516594915697-87eb3b1c14ea',title:['Um brinde ao pôr do sol','Un brindis al atardecer'],description:['Uma cesta, uma paisagem e tempo para simplesmente estar.','Una cesta, un paisaje y tiempo para simplemente estar.']},
 {id:'espumantes',city:'Garibaldi',category:'wine',price:110,hours:2,image:'photo-1510812431401-41d2bd2722f3',title:['O encontro das borbulhas','El encuentro de las burbujas'],description:['Descubra aromas e histórias em uma degustação de espumantes.','Descubra aromas e historias en una degustación de espumantes.']},
 {id:'caminhos',city:'Pinto Bandeira',category:'nature',price:85,hours:3,image:'photo-1472396961693-142e6e269027',title:['Caminhos de contemplação','Caminos de contemplación'],description:['Uma manhã entre o verde, trilhas leves e novos horizontes.','Una mañana entre el verde, senderos suaves y nuevos horizontes.']},
 {id:'sabores',city:'Garibaldi',category:'food',price:165,hours:2,image:'photo-1486297678162-eb2a19b0a32d',title:['Sabores que contam histórias','Sabores que cuentan historias'],description:['Queijos, pães e pequenos produtores em uma mesa regional.','Quesos, panes y pequeños productores en una mesa regional.']}
];
const dictionary={navExplore:'Experiencias',navRegion:'El territorio',navAgenda:'En temporada',route:'Mi itinerario',heroEyebrow:'29° S · 51° O / SERRA GAÚCHA',heroTitle:'El tiempo tiene<br>otro <em>sabor.</em>',heroDescription:'Entre viñedos, mesas e historias.<br>Encuentre su próximo recuerdo en la Serra Gaúcha.',discover:'Descubra experiencias',heroBottom:'PEQUEÑOS CAMINOS. GRANDES ENCUENTROS.',strip1:'Una selección con alma local',strip2:'De la tierra a su mesa',strip3:'Su próximo camino comienza aquí',collection:'01 / NUESTRA SELECCIÓN',experienceTitle:'Viva la Serra.<br><em>A su manera.</em>',experienceIntro:'Un brindis por lo que queda en la memoria.<br>Elija una experiencia y empiece a diseñar su camino.',search:'Buscar experiencias',city:'Ciudad',sort:'Ordenar',allCities:'Todas las ciudades',featured:'Nuestra selección',priceSort:'Menor precio',demoNotice:'Colección conceptual de portafolio. Experiencias, precios y disponibilidad son demostrativos; fotografías ilustrativas.',territoryEyebrow:'02 / UN LUGAR PARA PERTENECER',territoryTitle:'El mejor camino<br>es aquel que no quiere<br><em>recorrer con prisa.</em>',territoryText:'Colinas que guardan historias. Una mesa con lugar para alguien más. Explore tres destinos de la Serra y cree su propio itinerario.',officialGuide:'Conozca la guía oficial de turismo ↗',mapCaption:'SERRA GAÚCHA / MAPA ILUSTRATIVO · SIN ESCALA',seasonEyebrow:'03 / CADA ESTACIÓN, UN DESCUBRIMIENTO',seasonTitle:'La naturaleza tiene<br><em>su propio calendario.</em>',seasonNotice:'Guía estacional orientativa. Consulte cada establecimiento para fechas y programas reales.',closingEyebrow:'SU PRÓXIMO CAPÍTULO',closingTitle:'Algunos viajes terminan.<br><em>Otros se quedan con nosotros.</em>',buildRoute:'Cree su itinerario',footer:'Un proyecto conceptual de Dev Showcase.<br>Hecho con cuidado, para explorar sin prisa.',yourJourney:'SU PRÓXIMA HISTORIA',routeHint:'Organice los encuentros de cada día. Su itinerario se guarda en este navegador.',duration:'Duración del viaje',download:'Descargar itinerario',demoLabel:'DEMOSTRACIÓN',bookingTitle:'Imagine este encuentro.',bookingNotice:'Simule su visita. No se realizará ninguna reserva ni cobro y los datos no se enviarán.',visitDate:'Fecha de visita',guests:'Personas',simulate:'Simular visita'};
const original=new Map([...document.querySelectorAll('[data-i]')].map(el=>[el,el.innerHTML]));
let lang=0,category='all',bookingId=null,toastTimer;
let state={days:2,items:[]};
try{const stored=JSON.parse(localStorage.getItem('vindima-route-v1'));if(stored&&Array.isArray(stored.items)){state.days=[1,2,3].includes(stored.days)?stored.days:2;state.items=stored.items.filter((x,i,a)=>x&&experiences.some(e=>e.id===x.id)&&a.findIndex(y=>y?.id===x.id)===i).map(x=>({id:x.id,day:Math.max(1,Math.min(state.days,Number(x.day)||1))}));}}catch{}
const t=(pt,es)=>lang?es:pt;
const money=n=>new Intl.NumberFormat(lang?'es-BR':'pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const title=e=>e.title[lang];
const categories=()=>({all:t('Todas','Todas'),wine:t('Vinhos & espumantes','Vinos y espumantes'),food:t('À mesa','En la mesa'),nature:t('Ao ar livre','Al aire libre')});
const image=e=>e.id==='piquenique'?'assets/picnic-editorial.webp':e.id==='espumantes'?'assets/wine-editorial.webp':`https://images.unsplash.com/${e.image}?auto=format&fit=crop&w=900&q=80`;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
function persist(){try{localStorage.setItem('vindima-route-v1',JSON.stringify(state));}catch{toast(t('Roteiro disponível nesta sessão; armazenamento indisponível.','Itinerario disponible en esta sesión; almacenamiento no disponible.'));}$('#route-count').textContent=state.items.length;}
function save(id){const index=state.items.findIndex(x=>x.id===id);if(index<0)state.items.push({id,day:1});else state.items.splice(index,1);persist();renderCards();renderRoute();toast(index<0?t('Experiência adicionada ao roteiro.','Experiencia añadida al itinerario.'):t('Experiência removida do roteiro.','Experiencia eliminada del itinerario.'));}
function renderCategories(){$('#categories').innerHTML=Object.entries(categories()).map(([key,label])=>`<button class="chip" data-category="${key}" aria-pressed="${category===key}">${label}</button>`).join('');}
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function renderCards(){let rows=experiences.filter(e=>(category==='all'||e.category===category)&&(!$('#city').value||e.city===$('#city').value)&&normalize(`${title(e)} ${e.city} ${e.description[lang]}`).includes(normalize($('#search').value)));if($('#sort').value==='price')rows.sort((a,b)=>a.price-b.price);$('#results').textContent=`${rows.length} ${t('experiências para descobrir','experiencias para descubrir')}`;$('#cards').innerHTML=rows.length?rows.map((e,i)=>{const saved=state.items.some(x=>x.id===e.id);return `<article class="card reveal" style="animation-delay:${i*.04}s"><div class="card-image"><img src="${image(e)}" alt="${title(e)} — ${t('imagem ilustrativa','imagen ilustrativa')}" loading="lazy" width="600" height="480"><span class="tag">${categories()[e.category]}</span><button class="save" data-save="${e.id}" aria-pressed="${saved}" aria-label="${t('Salvar','Guardar')} ${title(e)}">${saved?'✓':'+'}</button></div><div class="card-body"><p class="card-location">${e.city} · ${e.hours}h</p><h3>${title(e)}</h3><p class="card-description">${e.description[lang]}</p><div class="card-bottom"><span><strong>${money(e.price)}</strong> / ${t('pessoa','persona')}</span><button data-details="${e.id}">${t('Conhecer','Descubrir')} ↗</button></div></div></article>`;}).join(''):`<div class="empty"><h3>${t('Um novo caminho?','¿Un nuevo camino?')}</h3><p>${t('Nenhuma experiência encontrada. Experimente outros filtros.','No se encontraron experiencias. Pruebe otros filtros.')}</p><button class="outline" id="reset-filters">${t('Limpar filtros','Limpiar filtros')}</button></div>`;}
function details(id){const e=experiences.find(x=>x.id===id);$('#detail-content').innerHTML=`<img src="${image(e)}" alt="${title(e)}"><p class="eyebrow">${e.city} · ${e.hours}h</p><h2 id="detail-title">${title(e)}</h2><p>${e.description[lang]}</p><p>${t('Inclui acompanhamento, uma experiência em grupo e tempo livre para aproveitar o lugar. Transporte não incluído. Atividades com bebidas alcoólicas são exclusivas para maiores de 18 anos.','Incluye acompañamiento, una experiencia en grupo y tiempo libre. Transporte no incluido. Las actividades con bebidas alcohólicas son exclusivas para mayores de 18 años.')}</p><p><strong>${money(e.price)}</strong> / ${t('pessoa · preço demonstrativo','persona · precio demostrativo')}</p><div class="detail-actions"><button class="button" data-book="${id}">${t('Simular visita','Simular visita')} ↗</button><button class="outline" data-save="${id}">${t('Adicionar / remover do roteiro','Añadir / quitar del itinerario')}</button></div><p class="disclosure">${t('Experiência fictícia. Não representa um estabelecimento real.','Experiencia ficticia. No representa un establecimiento real.')}</p>`;$('#details').showModal();}
function renderRoute(){$('#days').value=state.days;$('#route-items').innerHTML=state.items.length?state.items.map(x=>{const e=experiences.find(e=>e.id===x.id);return `<div class="route-row"><div><h3>${title(e)}</h3><p>${e.city} · ${e.hours}h · ${money(e.price)}</p><select data-day="${e.id}" aria-label="${t('Dia de','Día de')} ${title(e)}">${Array.from({length:state.days},(_,i)=>`<option value="${i+1}" ${x.day===i+1?'selected':''}>${t('Dia','Día')} ${i+1}</option>`).join('')}</select></div><button data-remove="${e.id}" aria-label="${t('Remover','Quitar')} ${title(e)}">${t('Remover','Quitar')}</button></div>`;}).join(''):`<div class="empty"><p>${t('Seu roteiro está esperando a primeira descoberta. Salve experiências pelo botão +.','Su itinerario espera el primer descubrimiento. Guarde experiencias con el botón +.')}</p><button class="outline" id="explore-from-route">${t('Explorar experiências','Explorar experiencias')} ↗</button></div>`;const total=state.items.reduce((sum,x)=>sum+experiences.find(e=>e.id===x.id).price,0);$('#route-total').textContent=state.items.length?`${t('Estimativa por pessoa','Estimación por persona')}: ${money(total)} · ${t('sem transporte e hospedagem','sin transporte ni alojamiento')}`:'';$('#download-route').disabled=!state.items.length;}
function openRoute(){renderRoute();$('#route-dialog').showModal();}
function renderExtras(){$('#places').innerHTML=['Bento Gonçalves','Garibaldi','Pinto Bandeira'].map((city,i)=>`<button class="place" data-place="${city}"><span>0${i+1} &nbsp; ${city}</span><span>↗</span></button>`).join('');const seasons=lang?[['ENE — MAR','Vendimia','Tiempo de cosecha y encuentros entre viñedos.'],['ABR — JUN','Colores de otoño','Paisajes dorados y mesas para quedarse.'],['JUL — SEP','Refugios de invierno','Vinos, sabores y conversaciones junto al fuego.'],['OCT — DIC','Aire de primavera','Jardines, paseos y almuerzos al aire libre.']]:[['JAN — MAR','Tempo de vindima','Colheitas e encontros entre os vinhedos.'],['ABR — JUN','Cores de outono','Paisagens douradas e mesas para ficar.'],['JUL — SET','Refúgios de inverno','Vinhos, sabores e conversas junto ao fogo.'],['OUT — DEZ','Ar de primavera','Jardins, passeios e almoços ao ar livre.']];$('#seasons').innerHTML=seasons.map(s=>`<article class="season-item"><small>${s[0]}</small><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('');}
function bookingTotal(){const e=experiences.find(x=>x.id===bookingId);const guests=Number($('#guests').value);$('#booking-total').textContent=e&&guests>=1&&guests<=12?`${t('Total simulado','Total simulado')}: ${money(e.price*guests)}`:'';}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.category){category=b.dataset.category;renderCategories();renderCards();}if(b.dataset.save)save(b.dataset.save);if(b.dataset.remove)save(b.dataset.remove);if(b.dataset.details)details(b.dataset.details);if(b.dataset.place){$('#city').value=b.dataset.place;category='all';$('#search').value='';renderCategories();renderCards();$('#experiencias').scrollIntoView();}if(b.id==='reset-filters'){category='all';$('#city').value='';$('#search').value='';renderCategories();renderCards();}if(b.id==='explore-from-route'){$('#route-dialog').close();$('#experiencias').scrollIntoView();}if(b.dataset.book){bookingId=b.dataset.book;$('#details').close();$('#booking-form').reset();$('#booking-status').textContent='';$('#booking-name').textContent=title(experiences.find(x=>x.id===bookingId));const now=new Date();$('#visit-date').min=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;bookingTotal();$('#booking').showModal();}});
$('#search').addEventListener('input',renderCards);$('#city').addEventListener('change',renderCards);$('#sort').addEventListener('change',renderCards);
$('#open-route').onclick=openRoute;$('#start-route').onclick=openRoute;
$('#days').onchange=()=>{state.days=Number($('#days').value);state.items.forEach(x=>x.day=Math.min(x.day,state.days));persist();renderRoute();};
$('#route-items').onchange=event=>{if(event.target.dataset.day){state.items.find(x=>x.id===event.target.dataset.day).day=Number(event.target.value);persist();}};
$('#guests').oninput=bookingTotal;$('#booking-form').onsubmit=event=>{event.preventDefault();$('#booking-status').textContent=t('Simulação concluída! Esta visita não está reservada. Adicione a experiência ao roteiro para guardar a ideia.','¡Simulación completada! Esta visita no está reservada. Añada la experiencia al itinerario para guardar la idea.');};
$('#download-route').onclick=()=>{const lines=['VINDIMA RS',t('Roteiro demonstrativo — nenhuma reserva realizada.','Itinerario demostrativo — ninguna reserva realizada.')];for(let day=1;day<=state.days;day++){lines.push('',`${t('Dia','Día')} ${day}`);state.items.filter(x=>x.day===day).forEach(x=>{const e=experiences.find(e=>e.id===x.id);lines.push(`${title(e)} — ${e.city} — ${e.hours}h — ${money(e.price)}`);});}lines.push('',$('#route-total').textContent);const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='vindima-roteiro.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#language').onclick=()=>{lang=1-lang;document.documentElement.lang=lang?'es':'pt-BR';original.forEach((html,el)=>el.innerHTML=lang?(dictionary[el.dataset.i]||html):html);$('#language').textContent=lang?'PT':'ES';$('#language').setAttribute('aria-label',lang?'Mudar para português':'Cambiar a español');$('#search').placeholder=t('Busque seu próximo encontro','Busque su próximo encuentro');document.querySelectorAll('[data-close]').forEach(el=>el.setAttribute('aria-label',t('Fechar','Cerrar')));[...$('#days').options].forEach((o,i)=>o.textContent=`${i+1} ${t(i?'dias':'dia',i?'días':'día')}`);renderCategories();renderCards();renderRoute();renderExtras();};
renderCategories();renderCards();renderRoute();renderExtras();$('#route-count').textContent=state.items.length;
